export const GAME = {
  INITIAL_LP: 8000,
  INITIAL_HAND_SIZE: 5,
  HAND_LIMIT: 6,
  MONSTER_ZONE_SIZE: 5,
  SPELL_TRAP_ZONE_SIZE: 5,
  TURN_TIME_LIMIT: 180,
  CHAIN_RESPONSE_TIME: 15,
  MAX_TIMEOUT_COUNT: 3,
  MAX_CHAIN_LENGTH: 16,
  TOTAL_BATTLE_TIME: 2400,
  SUDDEN_DEATH_LP_LOSS: 500,
  RECONNECT_TIMEOUT: 120,
  MATCHMAKING_TIMEOUT: 60,
} as const;

export const DECK = {
  MAIN_MIN: 40,
  MAIN_MAX: 60,
  EXTRA_MAX: 15,
  SIDE_MAX: 15,
  DEFAULT_COPY_LIMIT: 3,
} as const;

export const ELO = {
  DEFAULT_RATING: 1000,
  K_FACTOR_NEW: 32,
  K_FACTOR_NORMAL: 24,
  K_FACTOR_HIGH: 16,
  BASE_MATCH_RANGE: 100,
  EXPAND_PER_SEC: 10,
  MAX_MATCH_RANGE: 500,
} as const;
